In [2]:
import pandas as pd
import numpy as np

pd.options.display.max_columns = 100

df = pd.read_csv("/Users/mac/Downloads/lection1_materials/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head(10)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   
5  9305-CDSKC  Female              0      No         No       8          Yes   
6  1452-KIOVK    Male              0      No        Yes      22          Yes   
7  6713-OKOMC  Female              0      No         No      10           No   
8  7892-POOKP  Female              0     Yes         No      28          Yes   
9  6388-TABGU    Male              0      No        Yes      62          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   
5               Yes     Fiber optic             No           No   
6               Yes     Fiber optic             No          Yes   
7  No phone service             DSL            Yes           No   
8               Yes     Fiber optic             No           No   
9                No             DSL            Yes          Yes   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   
5              Yes          No         Yes             Yes  Month-to-month   
6               No          No         Yes              No  Month-to-month   
7               No          No          No              No  Month-to-month   
8              Yes         Yes         Yes             Yes  Month-to-month   
9               No          No          No              No        One year   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   
5              Yes           Electronic check           99.65        820.5   
6              Yes    Credit card (automatic)           89.10       1949.4   
7               No               Mailed check           29.75        301.9   
8              Yes           Electronic check          104.80      3046.05   
9               No  Bank transfer (automatic)           56.15      3487.95   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes  
5   Yes  
6    No  
7    No  
8   Yes  
9    No

In [3]:
df.shape

(7043, 21)

In [4]:
df['gender'].value_counts('Male')

Male      0.504756
Female    0.495244
Name: gender, dtype: float64

In [5]:
df['InternetService'].nunique()

3

In [6]:
df.describe()

SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [7]:
df['TotalCharges'].describe()

count     7043
unique    6531
top       20.2
freq        11
Name: TotalCharges, dtype: object

In [8]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [9]:
df['PhoneService'].replace('Yes', 1, inplace=True)
df['PhoneService'].replace('No', 0, inplace=True)

In [10]:
df['PhoneService']

0       0
1       1
2       1
3       0
4       1
       ..
7038    1
7039    1
7040    0
7041    1
7042    1
Name: PhoneService, Length: 7043, dtype: int64

In [11]:
df['TotalCharges']

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...   
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: object

In [12]:
np.where(df['TotalCharges'] == ' ')

(array([ 488,  753,  936, 1082, 1340, 3331, 3826, 4380, 5218, 6670, 6754]),)

In [13]:
df['TotalCharges'] = df['TotalCharges'].replace([' '], np.nan)

In [14]:
np.where(df['TotalCharges'] == ' ')

(array([], dtype=int64),)

In [15]:
np.where(df['TotalCharges'] == np.nan)

(array([], dtype=int64),)

In [16]:
df['TotalCharges'] = df['TotalCharges'].astype(np.float32)

In [17]:
df['TotalCharges'].dtype

dtype('float32')

In [18]:
df['TotalCharges'] = df['TotalCharges'].fillna(0)

In [19]:
np.where(df['TotalCharges'] == 0)

(array([ 488,  753,  936, 1082, 1340, 3331, 3826, 4380, 5218, 6670, 6754]),)

In [20]:
df['TotalCharges'].describe()

count    7043.000000
mean     2279.732178
std      2266.794434
min         0.000000
25%       398.549988
50%      1394.550049
75%      3786.599976
max      8684.799805
Name: TotalCharges, dtype: float64

In [21]:
df['Churn'].replace('Yes', 1, inplace=True)
df['Churn'].replace('No', 0, inplace=True)
df['Churn']

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [22]:
columns = ['StreamingMovies', 'StreamingTV', 'TechSupport']

for column in columns:
    df[column].replace('Yes', 1, inplace=True)
    df[column].replace('No', 0, inplace=True)
    df[column].replace('No internet service', 0, inplace=True)
    
df[['StreamingMovies', 'StreamingTV', 'TechSupport']]

StreamingMovies  StreamingTV  TechSupport
0                   0            0            0
1                   0            0            0
2                   0            0            0
3                   0            0            1
4                   0            0            0
...               ...          ...          ...
7038                1            1            1
7039                1            1            0
7040                0            0            0
7041                0            0            0
7042                1            1            1

[7043 rows x 3 columns]

In [23]:
df['PhoneService'].value_counts()

1    6361
0     682
Name: PhoneService, dtype: int64

In [24]:
df['PhoneService'].value_counts()[0] + df['PhoneService'].value_counts()[1]

7043

In [25]:
columns = ['gender', 'tenure', 'PhoneService', 'TotalCharges', 
           'StreamingMovies', 'StreamingTV', 'TechSupport', 'Churn']

columns_del = [x for x in df.columns if x not in columns]
columns_del

df.drop(columns_del, axis=1, inplace=True)
df.head(3)

gender  tenure  PhoneService  TechSupport  StreamingTV  StreamingMovies  \
0  Female       1             0            0            0                0   
1    Male      34             1            0            0                0   
2    Male       2             1            0            0                0   

   TotalCharges  Churn  
0     29.850000      0  
1   1889.500000      0  
2    108.150002      1

In [26]:
from sklearn.model_selection import train_test_split

features = ['gender', 'tenure', 'PhoneService', 'TotalCharges', 'StreamingMovies', 'StreamingTV', 'TechSupport']
target = 'Churn'

X_train, X_test, y_train, y_test = train_test_split(df[features], df[target], test_size=0.2, random_state=42)

In [27]:
X_train

gender  tenure  PhoneService  TotalCharges  StreamingMovies  \
2142  Female      21             1   1336.800049                1   
1623  Female      54             1   5129.450195                1   
6074    Male       1             0     23.450001                0   
1362    Male       4             1    237.949997                0   
6754    Male       0             1      0.000000                0   
...      ...     ...           ...           ...              ...   
3772    Male       1             1     95.000000                1   
5191  Female      23             1   2198.300049                1   
5226    Male      12             1    306.049988                0   
5390    Male      12             1   1200.150024                1   
860     Male      26             1    457.299988                0   

      StreamingTV  TechSupport  
2142            0            0  
1623            1            0  
6074            0            0  
1362            0            0  
6754            0            1  
...           ...          ...  
3772            1            0  
5191            1            1  
5226            0            0  
5390            1            0  
860             0            0  

[5634 rows x 7 columns]

In [28]:
y_train

2142    0
1623    0
6074    1
1362    1
6754    0
       ..
3772    1
5191    0
5226    0
5390    1
860     0
Name: Churn, Length: 5634, dtype: int64

In [29]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

class ColumnSelector(BaseEstimator, TransformerMixin):
    """
    Transformer to select a single column from the data frame to perform additional transformations on
    """
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[self.key]
    
class NumberSelector(BaseEstimator, TransformerMixin):
    """
    Transformer to select a single column from the data frame to perform additional transformations on
    Use on numeric columns in the data
    """
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[[self.key]]
    
class OHEEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, key):
        self.key = key
        self.columns = []

    def fit(self, X, y=None):
        self.columns = [col for col in pd.get_dummies(X, prefix=self.key).columns]
        return self

    def transform(self, X):
        X = pd.get_dummies(X, prefix=self.key)
        test_columns = [col for col in X.columns]
        for col_ in test_columns:
            if col_ not in self.columns:
                X[col_] = 0
        return X[self.columns]

gender = Pipeline([
                ('selector', ColumnSelector(key='gender')),
                ('ohe', OHEEncoder(key='gender'))
            ])

In [30]:
gender.fit_transform(X_train)
gender

Pipeline(steps=[('selector', ColumnSelector(key='gender')),
                ('ohe', OHEEncoder(key='gender'))])

In [31]:
from sklearn.preprocessing import StandardScaler

tenure =  Pipeline([
                ('selector', NumberSelector(key='tenure')),
                ('standard', StandardScaler())
            ])

In [32]:
TotalCharges =  Pipeline([
                ('selector', NumberSelector(key='TotalCharges')),
                ('standard', StandardScaler())
            ])

TotalCharges

Pipeline(steps=[('selector', NumberSelector(key='TotalCharges')),
                ('standard', StandardScaler())])

In [33]:
from sklearn.pipeline import FeatureUnion

number_features = Pipeline([
                ('selector', ColumnSelector(key=['PhoneService',
                                                 'StreamingMovies', 'StreamingTV', 
                                                 'TechSupport']))
            ])

number_features

Pipeline(steps=[('selector',
                 ColumnSelector(key=['PhoneService', 'StreamingMovies',
                                     'StreamingTV', 'TechSupport']))])

In [34]:
feats = FeatureUnion([('tenure', tenure),
                      ('TotalCharges', TotalCharges),
                      ('continuos_features', number_features),
                      ('gender', gender)])
feature_processing = Pipeline([('feats', feats)])

In [35]:
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline([
    ('features',feats),
    ('classifier', RandomForestClassifier(random_state = 42)),
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('features',
                 FeatureUnion(transformer_list=[('tenure',
                                                 Pipeline(steps=[('selector',
                                                                  NumberSelector(key='tenure')),
                                                                 ('standard',
                                                                  StandardScaler())])),
                                                ('TotalCharges',
                                                 Pipeline(steps=[('selector',
                                                                  NumberSelector(key='TotalCharges')),
                                                                 ('standard',
                                                                  StandardScaler())])),
                                                ('continuos_features',
                                                 Pipeline(steps=[('selector',
          

In [36]:
pred_prob = pipeline.predict_proba(X_test)
pred_prob

array([[0.26, 0.74],
       [1.  , 0.  ],
       [1.  , 0.  ],
       ...,
       [0.92, 0.08],
       [0.99, 0.01],
       [0.04, 0.96]])

In [37]:
from sklearn.metrics import roc_auc_score, log_loss

pipeline.score(X_test, y_test)

0.7771469127040455

In [38]:
pred_prob[:,0]

array([0.26, 1.  , 1.  , ..., 0.92, 0.99, 0.04])

In [39]:
roc_auc_score(y_test, pred_prob[:,1])

0.801332977941557

In [40]:
log_loss(y_test, pred_prob[:,1])

0.6072124715712782